# Generated by Django 3.1.7 on 2021-03-01 15:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_updateprofile_profile_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UpdateProfile',
            new_name='Profile',
        ),
    ]
